CREATE TABLE IF NOT EXISTS sessions (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGSERIAL NOT NULL,
	access_token TEXT NOT NULL,
	refresh_token TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id)
);
